Mh/mapreduce
JuliaGPU/Metal.jl pull request #10
Opened 2022-04-22 10:02 UTC by max-Hawkins

This implements some of the key components for mapreduce capabilities. Waiting on argument passing to mature before fully implementing.

2022-04-27 10:38 UTC, maleadt requested changes

2022-04-27 10:38 UTC, maleadt commented on examples/peaktransfer.jl
> +    out[idx] = in[idx]
You'd want manual bounds checking (`if idx < length(out)` or so) and an `@inbounds` here to avoid potential exceptions.

2022-04-27 10:38 UTC, maleadt commented on examples/vadd.jl
> +Metal.@sync @metal threads=len vadd(d_a, d_b, d_c)
The `@sync` shouldn't be necessary? Unrelated to this commit, and the `Array` below should be synchronizing.

2022-04-27 10:38 UTC, maleadt commented on src/device/metal/memory_shared.jl
> +        # Metal threadgroup memory alignment is 16, so use that
You're not, though? Out of date comment?

2022-04-27 10:38 UTC, maleadt commented on src/mapreduce.jl
> +Base.@propagate_inbounds _map_getindex(args::Tuple, I) = ((args[1][I]), _map_getindex(Base.tail(args), I)...)
What are these for? Not used in this commit?

2022-04-27 10:38 UTC, maleadt commented on examples/peaktransfer.jl
> +    _grid = cld(_size, 1024)
Is there no upper limit on the number of threads (e.g, depending on the register/shared memory usage)?

2022-05-02 08:17 UTC, max-Hawkins commented on examples/peaktransfer.jl
> +    _grid = cld(_size, 1024)
There is, but for this kernel, I know the number of threads isn't less than the maximum. I could put in a check after compiling but not launching before the actual execution. There are launch-side checks on not over dispatching threadgroups though. Let me know what you'd want.

2022-05-04 07:31 UTC, maleadt commented on examples/peaktransfer.jl
> +    _grid = cld(_size, 1024)
Why a check? Can't we consult the max thread count and use that, like CUDA.jl's launch configuration?

2022-05-04 11:47 UTC, max-Hawkins commented on examples/peaktransfer.jl
> +    _grid = cld(_size, 1024)
Let me know if the updates resolved this. I implemented it similarly to CUDA.jl.

2022-05-04 11:56 UTC, maleadt commented on src/execution/kernel.jl
> +    # TODO: Be more efficient about creating pipeline states as they're expensive
One possibility would be to put the pipeline in the MtlKernel object, so that it's only created once (and we can easily reuse it when needed). Doesn't need to happen in this PR htough.

2023-01-23 05:31 UTC, closed without merging