GPU Frame Tracing
JuliaGPU/Metal.jl pull request #11
Opened 2022-04-28 08:52 UTC by max-Hawkins

This will allow developers to capture frame traces directly from Julia using either a profile macro or lower-level APIs.

2022-04-28 09:00 UTC, maleadt requested changes

2022-04-28 09:00 UTC, maleadt commented on cmt/src/capture/capture_manager.m
> +mtStopCapture(MtCaptureManager *manager){
The API availability ranges seem wrong here, e.g., this call is ios 11.0/macos 10.13: https://developer.apple.com/documentation/metal/mtlcapturemanager/2869736-stopcapture. Can you verify you used the correct ranges everywhere?

2022-04-28 09:00 UTC, maleadt commented on lib/core/profile.jl
> +Profile Metal/GPU work using XCode's GPU frame capture capabilities.\n
Why the `\n` and `\\` escapes etc?

2022-04-28 09:00 UTC, maleadt commented on lib/core/profile.jl
> +Note: Metal frame capture must be enabled before launching Julia (METAL\\_CAPTURE\\_ENABLED=1) \
We can just detect this env var and warn, right? Probably shouldn't error, but warn at least.

2022-04-28 09:00 UTC, maleadt commented on lib/core/profile.jl
> +                isdir(dir) && throw(ArgumentError("`dir` keyword argument to @profile should not be an existing directory"))
Ideally, this is the kind of stuff we should do at run time so that the `dir` argument doesn't need to be a literal string. `startCapture` can just perform those checks.

2022-04-28 09:00 UTC, maleadt commented on lib/core/profile.jl
> +    destination == MtCaptureDestinationGPUTraceDocument && folder == nothing && throw(ArgumentError("Must specify output folder if destination is GPUTraceDocument"))
Better wrap long lines at around 92 chars.

2022-04-28 09:00 UTC, maleadt commented on lib/core/profile.jl
> +        err.domain == "MTLCaptureError" && err.code == 1 && println("Error: Did you set the Metal capture environment variable before launching Julia? \
Use `"""` instead of escaping endlines.

2022-04-28 09:00 UTC, maleadt commented on lib/core/profile.jl
> +        err.domain == "MTLCaptureError" && err.code == 1 && println("Error: Did you set the Metal capture environment variable before launching Julia? \
Also, why the `println` and `throw`? We support nested exceptions nowadays, so you can just throw an exception capturing the child MtlError.

2022-04-28 09:00 UTC, maleadt commented on test/runtests.jl
> +    # Capture manager support depends on XCode and environment variable, so don't test
Spawn a new Julia? CUDA.jl has a bunch of tests like that, so you can copy the utility function for launching a new Julia session in the same environment.

2022-04-28 09:03 UTC, max-Hawkins commented on lib/core/profile.jl
> +Note: Metal frame capture must be enabled before launching Julia (METAL\\_CAPTURE\\_ENABLED=1) \
I originally had that in, but capturing can be enabled by other means than just the environment variable (Info.plist and XCode directly for example). Should I put in a warn message anyway since those other scenarios are less likely?

2022-04-28 09:10 UTC, max-Hawkins commented on lib/core/profile.jl
> +Profile Metal/GPU work using XCode's GPU frame capture capabilities.\n
The first one was me being stupid, but the \\ are needed so that the underscores aren't rendered as CAPTURE underlined.

2022-04-28 09:26 UTC, max-Hawkins commented on lib/core/profile.jl
> +Note: Metal frame capture must be enabled before launching Julia (METAL\\_CAPTURE\\_ENABLED=1) \
There's also the error message in start capture that alerts the user about the environment variable if the 'capture not supported' error is thrown.

2022-04-28 09:32 UTC, maleadt commented on lib/core/profile.jl
> +Note: Metal frame capture must be enabled before launching Julia (METAL\\_CAPTURE\\_ENABLED=1) \
Yeah I read that later, should be fine to just warn there.

2022-04-28 09:49 UTC, max-Hawkins commented on cmt/src/capture/capture_descriptor.m
> +// TODO: Alter return type: Could be MTLDevice, MTLCommandQueue, or MTLCaptureScope
How do I properly handle the different possible return types here?

2022-04-28 09:59 UTC, maleadt commented on cmt/src/capture/capture_descriptor.m
> +// TODO: Alter return type: Could be MTLDevice, MTLCommandQueue, or MTLCaptureScope
You have the same problem below (with the setter), right? With that function, you can just provide 3 different methods. For the getter, you can return a void* and use an output flag indicating the type of object (e.g. using an enum).

2022-04-28 20:22 UTC, max-Hawkins commented
@maleadt Just amended the mentioned pieces of code. Will you take another look?

2022-05-11 07:08 UTC, maleadt commented on lib/core/profile.jl
> +const MTLCaptureScope = Ptr{MtCaptureScope}
Can't this be used to implement something like CUDA.jl's `CUDA.@profile`, where the code in that block is the only code that will be profiled (or, in the case of Metal, it will be using a separate scope so that you can filter on it from XCode)?

2022-11-07 20:16 UTC, closed without merging