Add `MPSMatrixRandom`
JuliaGPU/Metal.jl pull request #321
Opened 2024-03-26 00:27 UTC by christiangnrd

Adds https://developer.apple.com/documentation/metalperformanceshaders/mpsmatrixrandom?language=objc and the other classes that start with "MPSMatrixRandom".

Code to integrate with `Random.jl` functions is present but commented out because it seems to be slower than the current `rand!` functionality from GPUArrays.

2024-03-27 12:22 UTC, maleadt commented
> Code to integrate with `Random.jl` functions is present but commented out because it seems to be slower than the current `rand!` functionality from GPUArrays.

The quality of random numbers produced by GPUArrays' RNG is probably lower though, so I would consider just using the one from MPS.

2024-03-27 20:38 UTC, christiangnrd commented
A few comments.

- I did some stuff to get `rand` to work on all supported Integer types. Is this valid or does it affect the quality of random numbers?
- Every buffer is now created to a multiple of 16 bytes as the random number generation generates 32-bit values in multiples of 4. Is this acceptable? Is there an better alternative?
- I'm not sure how to approach seeding. Any ideas?
- Float 16 numbers are the only values that don't use MPS. Should there be a warning somewhere mentioning this?

2024-03-29 09:42 UTC, maleadt commented on lib/mps/matrix.jl
> +if macos_version() >= v"14" && isdefined(Core, :BFloat16)
BFloat16 can be supported by depending on BFloat16s.jl; the fact that Core provides a type is an implementation detail.

2024-03-29 09:45 UTC, maleadt commented on lib/mps/vector.jl
> +@inline function mpsvector(arr::MtlArray{T}, ::Type{T2}, len) where {T,T2}
These are questionable methods...

2024-03-29 10:04 UTC, maleadt commented
> I did some stuff to get `rand` to work on all supported Integer types. Is this valid or does it affect the quality of random numbers?

So you're just reinterpreting Float32-generated random numbers as integers? That doesn't seem valid. Naively I would try to map the generated [0, 1) numbers to the integer's range, but that may still result in a biased output. I'm no RNG expert, but you could try it out and comparing a histogram to `Random.RNG` and see if it looks somewhat acceptable.

> I'm not sure how to approach seeding. Any ideas?

What is the problem? Doesn't it have a way to seed the generator (e.g. https://developer.apple.com/documentation/metalperformanceshaders/mpsmatrixrandomphilox/3242872-initwithdevice?language=objc)?

> * Float 16 numbers are the only values that don't use MPS
> * MPSMatrixRandom requires buffer offset to also be a multiple of 4

I would just fall back to the GPUArrays RNG in those cases. CUDA.jl similarly tries to CURAND when possible, and falls back to the native generator in other cases.

2024-03-29 14:04 UTC, christiangnrd commented on lib/mps/matrix.jl
> +if macos_version() >= v"14" && isdefined(Core, :BFloat16)
I removed the `isdefined` check and made the statement an extension for BFloat16s.jl.

2024-03-30 04:58 UTC, christiangnrd commented
> So you're just reinterpreting Float32-generated random numbers as integers?

The default rng generator generates random UInt32 values so it's reinterpreting those as whatever Integer value was determined. Just took a look at histograms for all Integer datatypes and they all seem to be equivalent to the CPU versions. They also seem to be much better than the GPUArrays.

Ex:
![blah](https://github.com/JuliaGPU/Metal.jl/assets/28689358/626c3150-2aa7-4618-a096-270eb62b79cb)


> What is the problem?

I'm not sure how to tie it in with `Metal.seed!` to access the rng state and such.

I've marked this as a draft because the seeding test is currently marked as broken and I don't want to forget to fix it.

2024-03-30 05:00 UTC, christiangnrd commented on lib/mps/vector.jl
> +@inline function mpsvector(arr::MtlArray{T}, ::Type{T2}, len) where {T,T2}
Either I'm going crazy or the random functions seem to treat the MPSVector offset field as element offset instead of byte offset so I gave up on any views (`offset != 0`) using the MPS random functions.

2024-03-30 10:49 UTC, maleadt commented
> They also seem to be much better than the GPUArrays.

That's not surprising :-) FYI, if you _really_ want to make sure the RNG is good, you can use https://github.com/JuliaRandom/RNGTest.jl. CUDA.jl's native RNG passes those, but it took a while to get there.

2024-04-01 16:27 UTC, christiangnrd commented
This is now ready for final review. It should not be squashed when merging because there are a few general improvements that are not directly related to the main focus of this PR. I made sure to have all the commits make sense on their own.

2024-04-03 08:03 UTC, maleadt requested changes
Looking good!

2024-04-03 08:03 UTC, maleadt commented on src/random.jl
> +@inline function usempsrandom(A::MtlArray{T}) where {T}
```suggestion
@inline function can_use_mpsrandom(A::MtlArray{T}) where {T}
```

2024-04-03 08:05 UTC, maleadt commented on lib/mps/vector.jl
> +@inline function mpsvector(arr::MtlArray{T}, ::Type{T2}, len) where {T,T2}
Can't we treat it like an element offset argument then?

2024-04-03 13:28 UTC, christiangnrd commented
I've fixed the easy to fix comments. I'll go over the rest over the weekend when I have more time.

2024-04-04 03:57 UTC, christiangnrd commented on lib/mps/vector.jl
> +    @objc [vecormat::id{M} synchronizeOnCommandBuffer:cmdBuf::id{MTLCommandBuffer}]::Nothing
I'll remove them from this PR and they can be added later if needed.

2024-04-04 21:05 UTC, christiangnrd commented on test/metal.jl
> +@test sizeof(buf) == 16
Fixed.

2024-04-04 21:06 UTC, christiangnrd commented on lib/mtl/buffer.jl
> +@inline bufferbytesize(bytesize::T) where {T <: Integer} = ceil(T, bytesize / BUFFER_ALIGNMENT_FOR_RAND) * T(BUFFER_ALIGNMENT_FOR_RAND)
Renamed to BUFFER_PADDING_FOR_RAND and no longer by default

2024-04-04 21:07 UTC, christiangnrd commented on lib/mps/random.jl
> +    update_state!(rng,length(A))
For some reason I didn't think you could reuse kernels. Now fixed.

2024-04-04 21:08 UTC, christiangnrd commented on docs/src/usage/array.md
> +    Do not use `Random.rand(::MPS.RNG, args...)` or `Random.randn(::MPS.RNG, args...)` on views as you will most likely overwrite values outside of the view due to limitations in random number genera
I'll add the issue once this is merged in case any of the specifics change.

2024-04-04 21:08 UTC, christiangnrd commented on lib/mps/matrixrandom.jl
> +    wait_completed(cmdBuf)
Fixed

2024-04-04 21:22 UTC, christiangnrd commented on lib/mps/vector.jl
> +@inline function mpsvector(arr::MtlArray{T}, ::Type{T2}, len) where {T,T2}
I agree this definitely feels wrong. I came up with another approach that uses reinterpret, but since the buffer size has to be a multiple of 16, I end up having to do some weird stuff like replacing the `dims` field of a view which feels just as wrong but in a different way. This approach also breaks rand on views even more because the GPUArrays `reinterpret` [resets the offset](https://github.com/JuliaGPU/GPUArrays.jl/blob/462322603cae08520a2297798c026f3be259df12/src/host/base.jl#L176).

I'm open to suggestions. Maybe this approach stays for this PR and I open an issue to use the other approach once the `reinterpret` bug is fixed?

2024-04-04 21:22 UTC, christiangnrd commented on lib/mps/random.jl
> +end
Fixed.

2024-04-07 20:21 UTC, christiangnrd commented on lib/mps/vector.jl
> +@inline function mpsvector(arr::MtlArray{T}, ::Type{T2}, len) where {T,T2}
I filed a report with Apple since this is also the case when using Swift. I worked around it with the `MPSTemporaryVector` solution for views.

2024-04-07 22:03 UTC, christiangnrd commented on lib/mps/vector.jl
> +@inline function mpsvector(arr::MtlArray{T}, ::Type{T2}, len) where {T,T2}
Moved the discussion to now-relevant code.

2024-04-10 18:38 UTC, maleadt commented on test/random.jl
> +        Metal.seed!(123)
Why does the global RNG need seeding if you're using an explicit RNG object below?

2024-04-11 08:19 UTC, maleadt commented on test/random.jl
> +        Metal.seed!(123)
Wait, what? Can you elaborate?

2024-04-15 22:10 UTC, christiangnrd commented
Failure unrelated (#329)

2024-04-16 20:11 UTC, christiangnrd commented
I don't understand how the 1.9 failure could be related but it's the second time it happens. Any ideas?

[Failure 1](https://buildkite.com/julialang/metal-dot-jl/builds/947#018ee3aa-18e2-472c-b93f-f77451e3f87a)
[Failure 2](https://buildkite.com/julialang/metal-dot-jl/builds/949#018ee877-666a-430c-ba84-6d587d8687ca)

2024-04-17 06:27 UTC, maleadt commented
That's a GPUCompiler issue, unrelated to this PR.

2024-04-29 07:54 UTC, tgymnich approved these changes

2024-04-29 07:54 UTC, tgymnich commented on lib/mps/matrixrandom.jl
> +    # mentions that both must be multiples of 4 bytes in MacOS so error when they are not
We should rather add a warning or assertion to `append_copy` directly.

2024-05-24 13:32 UTC, maleadt commented on docs/src/usage/array.md
> +    `Random.rand!(::MPS.RNG, args...)` andc `Random.randn!(::MPS.RNG, args...)` have a framework limitation that requires the byte offset and byte size of the destination array to be a multiple of 4.
```suggestion
    `Random.rand!(::MPS.RNG, args...)` and `Random.randn!(::MPS.RNG, args...)` have a framework limitation that requires the byte offset and byte size of the destination array to be a multiple of 4.
```

2024-05-24 13:32 UTC, maleadt commented on lib/mps/matrixrandom.jl
> +    # XXX: who releases this object?
```suggestion
    # XXX: who releases this object?
```

Should this be a GC-managed object? I think we can (and should) safely `release` it after having used it to create an MPSRandom object.

2024-05-24 13:32 UTC, maleadt commented on lib/mps/matrixrandom.jl
> +    # XXX: who releases this object?
```suggestion
```

2024-05-24 13:32 UTC, maleadt commented on lib/mps/matrixrandom.jl
> +    # XXX: who releases this object?
```suggestion
```

2024-05-24 13:32 UTC, maleadt commented on lib/mps/matrixrandom.jl
> +    # XXX: who releases this object?
```suggestion
```

2024-08-27 09:22 UTC, maleadt reviewed
Sorry, hadn't seen the request for review.

2024-08-27 09:22 UTC, maleadt commented on test/random.jl
> +        Metal.seed!(123)
This is still too fishy for me. Do we have an issue open about it? Removing the seeding doesn't make the tests fail here...

2024-08-27 09:22 UTC, maleadt commented on test/random.jl
> +            @test iszero(collect(a) - collect(b)) broken = (T == Float16 && d == (1000,1000))
Why not simply `@test Array(a) == Array(b) ...`?

2024-08-27 18:04 UTC, maleadt commented
Interesting failure; seems unrelated to this PR though. I've restarted the job.

2024-08-27 18:55 UTC, christiangnrd commented
Once the unrelated failure is resolved, this should be ready to merge. The only thing left is that at the moment the docs mention that this is available starting with Metal 2.0, which I wrote when I thought #392 would cause a major version bump, but this doesn't have any breaking changes so it should probably be 1.4 instead.

2024-08-27 20:28 UTC, maleadt approved these changes

2024-08-27 20:28 UTC, merged

2024-08-27 20:29 UTC, maleadt commented
Great stuff, thanks for keeping at it! We should include this in a blog post when releasing the next version of Metal.jl; I'll ping you when I get to that.

2024-08-27 20:31 UTC, christiangnrd commented
Thanks for taking the time to review this over and over!